### PR TITLE
OPAM: added build instructions and deps for documentation

### PR DESCRIPTION
**Pull request by pdonadeo**

### CODE REVIEW

**Comment by Freyr666** [comment]
Well, as @dbuenzli mentioned [here](https://discuss.ocaml.org/t/help-needed-with-obus/5049/7?u=freyr666), this shouldn't affect the generated docs. But overall it seems fine.

**Comment by pdonadeo** [comment]
For sure I had no documentation installed on my PC at home. So I patched the repo, locally installed it with `opam install .` and the documentation appeared.

So I wrongly deduced that 2 + 2 = 22.

Today, on the office PC, the documentation is present and I cannot reproduce the problem I saw yesterday.

**Comment by pmetzger** [comment]
So is this fixing a real problem or not?

**Comment by dbuenzli** [comment]
No it's not.

**Comment by pdonadeo** [comment]
No, it's not a real problem or at least I saw it only once and cannot reproduce. I'm going to close.

**Comment by pmetzger** [comment]
Thanks, @pdonadeo.

**Pull request closed without merging**
